version: '3.9'

services:
  # Backend Service (Laravel)
  backend:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    container_name: laravel_backend
    volumes:
      - ./back-end:/var/www/html
    ports:
      - "8088:8000"
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=task_manager
      - DB_USERNAME=postgres
      - DB_PASSWORD=secret
    depends_on:
      - db

  # Database Service (PostgreSQL)
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      - POSTGRES_DB=task_manager
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # Frontend Service (Remix)
  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    container_name: remix_frontend
    volumes:
      - ./front-end:/app
    ports:
      - "3000:3000"
    environment:
      - API_URL=http://backend:8000
    depends_on:
      - backend
    command: ["npm", "run", "dev"]

  # Nginx Service (Reverse Proxy)
  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - frontend
    restart: always

  # pgAdmin Service
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8081:80"
    depends_on:
      - db

networks:
  default:
    driver: bridge

volumes:
  pgdata:
    driver: local
